@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6InVsdGVybmFlIiwiaWQiOiIxMTE4MDIzMzkzOTE0MjkxOTc5MDUiLCJlbWFpbCI6InVsdGVybmFlQGdtYWlsLmNvbSIsImlhdCI6MTcxODk4MDczMywiZXhwIjoxNzE5MDY3MTMzfQ.3VAPXhYMGA9r1ggdgQWHIgpwCYfGB6KoD-dIMBQ9PIY
@authorizationUser2 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6InVsdGlzYWVyIHJldnRlcm5hZSIsImlkIjoiMTA2NjE2ODU4MDc5MTY5NTQ5MzA0IiwiZW1haWwiOiJ1bHRpc2Flci5yZXZ0ZXJuYWVAZ21haWwuY29tIiwiaWF0IjoxNzE4OTgyMTA5LCJleHAiOjE3MTkwNjg1MDl9.C4iORenbbbGVOomoiWQU8HgLUrqI14BSJECUkOVRjGM
@authorizationUser3 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6Impob25hdGFuIGNhc3RpbGxvIiwiaWQiOiIxMDM2ODk0MjIwNjM5MTc1MTMzMTgiLCJlbWFpbCI6IjAwMXNhcmdlbnRvMDAxQGdtYWlsLmNvbSIsImlhdCI6MTcxODk4NDc4MCwiZXhwIjoxNzE5MDcxMTgwfQ.ED0c5VwvhaRgQJStkIzK-_pSfWrCKtgJguVwn3GyYO8
@baseUrl = http://localhost:3000

@user1 = 106616858079169549304
@user2 = 111802339391429197905
@user3 = 109838121142820694014
@user4 = 103689422063917513318
@user5 = 114508850062700611993
@user6 = e0febc03-18f3-4ad3-ba88-2266fc3c3a51

@group_id = d9c13f9f-2a26-4304-8129-233045ad28e1
@member_id = b09d180b-f031-4139-99a5-545eb076a41e
@moderator_id = 106616858079169549304
@chat_id = 5f1e46a8-1bca-47a1-98e5-44b7335538f6

@username = Ultisaer123
@password = 123456
@email = Ultisaer123@gmail.com
@nickname = 'Ultis'

@urlAvatar = 'https://route.com

// -------------------- Profile ------------------------ //

### Profile
GET {{baseUrl}}/profile HTTP/1.1
Content-Type: application/json
Authorization: {{authorizationUser2}}

// -------------------- Register ----------------------- //

### Register
POST {{baseUrl}}/register  HTTP/1.1
Content-Type: application/json

{
  "password": "{{password}}",
  "email": "{{email}}",
  "nickname": "{{nickname}}"
}

### Register google
POST {{baseUrl}}/register/google
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "email": "{{email}}",
  "nickname": "{{nickname}}",
  "avatar_id": 1
}

// -------------------- Login -------------------------- //

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "nickname": "{{nickname}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

// -------------------- Profile ------------------------ //

### getProfile
GET {{baseUrl}}/profile HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

### updateProfile
POST {{baseUrl}}/login
Content-Type: application/json
Authorization: {{authorization}}

{
  "username": "{{username}}",
  "password": "{{password}}",
  "email": "{{email}}",
  "nickname": "{{nickname}}",
  "avatar_id": 9
}

// -------------------- Avatars ------------------------ //
### getAvatar
GET {{baseUrl}}/avatars
Content-Type: application/json
Authorization: {{authorization}}


### getAvatar_id
GET {{baseUrl}}/avatars/8
Content-Type: application/json
Authorization: {{authorization}}

### create_avatar
POST {{baseUrl}}/avatars
Content-Type: application/json
Authorization: {{authorization}}

{
  "url" : "{{urlAvatar}}"
}

// -------------------- Friends ------------------------ //
### send_request_friend
POST  {{baseUrl}}/friends
Content-Type: application/json
Authorization: {{authorizationUser2}}

{
  "friend_id" : "{{user2}}"
}

### Friends get all
GET {{baseUrl}}/friends
Content-Type: application/json
Authorization: {{authorization}}

### Friends updateStatus aceptar o rechazar la solicitud de amistas
PUT {{baseUrl}}/friends/{{user6}}/accepted
Content-Type: application/json
Authorization: {{authorization}}

### Friend delete
DELETE {{baseUrl}}/friends/{{user6}}
Content-Type: application/json
Authorization: {{authorization}}

// -------------------- Chat --------------------------- //
### Craete_chat
POST {{baseUrl}}/chats
Content-Type: application/json
Authorization: {{authorization}}

{
  "friend_id" : "{{user4}}"
}

### List chats
GET {{baseUrl}}/chats
Content-Type: application/json
Authorization: {{authorization}}

### detailsChatById -- ver diferencias entre chat 1 v 1 y grupal
GET {{baseUrl}}/chats/{{chat_id}}
Content-Type: application/json
Authorization: {{authorization}}

### sendMessage
POST {{baseUrl}}/chats/{{chat_id}}/messages
Content-Type: application/json
Authorization: {{authorization}}

{
  "content": "GG"
}

### sendMessageUser2
POST {{baseUrl}}/chats/{{chat_id}}/messages
Content-Type: application/json
Authorization: {{authorizationUser2}}

{
  "content": "asd"
}

### sendMessageUser3
POST {{baseUrl}}/chats/{{chat_id}}/messages
Content-Type: application/json
Authorization: {{authorizationUser3}}

{
  "content": "3"
}

### getAllMessages
GET {{baseUrl}}/chats/{{chat_id}}/messages
Content-Type: application/json
Authorization: {{authorization}}

// -------------------- Grupos ------------------------- //
### createGroup
POST {{baseUrl}}/groups HTTP/1.1
Content-Type: application/json
Authorization: {{authorizationUser2}}

{
  "name": "Grupo publico de Ultisaer",
  "description": "JIJIJIJA",
  "is_public": true,
  "sql" : "DROP TABLE users"
}

### getAllGroups
GET {{baseUrl}}/groups HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

### getGroupById
GET {{baseUrl}}/groups/{{group_id}} HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

### updateGroup
PATCH  {{baseUrl}}/groups/{{group_id}} HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

{
  "name": "elinia Update ",
  "description": "New description"
}

### deleteGroup
DELETE  {{baseUrl}}/groups/{{group_id}} HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

// -------------------- Grupos Members ----------------- //

### addMembers
POST {{baseUrl}}/groups/{{group_id}}/members HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

{
  "users_ids": [
    "IMPOSTOR",
    "{{user1}}",
    "{{user2}}",
    "{{user3}}",
    "{{user5}}" 
  ]
}

### deleteMember
DELETE  {{baseUrl}}/groups/{{group_id}}/members/{{user3}} HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

### deleteAllMembers
DELETE  {{baseUrl}}/groups/{{group_id}}/members/all HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

// -------------------- Grupos Moderatos --------------- //

### assigmentModerators
POST {{baseUrl}}/groups/{{group_id}}/moderators HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

{
  "users_ids": [
    "{{user1}}" ,
    "{{user5}}",
    "{{user4}}" ,
    "Importor"
  ]
}
### deleteModerator
DELETE  {{baseUrl}}/groups/{{group_id}}/moderators/{{user4}} HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

### deleteAllModerators
DELETE  {{baseUrl}}/groups/{{group_id}}/moderators/all HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

// ---------------------------- Group Chats 

### Createchat
POST {{baseUrl}}/groups/{{group_id}}/chats HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

{
  "name" : "Chat Conectado SUPERR",
  "chat_users" : [ 
    "{{user1}}",
    "{{user2}}",
    "{{user3}}",
    "{{user4}}",
    "Impostor"
  ]
}

### Get Chats in Group
GET {{baseUrl}}/groups/{{group_id}}/chats HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

### Get Chat Details in Group
GET {{baseUrl}}/groups/{{group_id}}/chats/{{chat_id}} HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

### Update Chat in Group
PATCH {{baseUrl}}/groups/{{group_id}}/chats/{{chat_id}} HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

{
  "name": "NuevoNombreDelChat",
  "chat_users": ["{{user1}}", "{{user2}}", "impostor", "{{user4}}" , "{{user5}}"]
}

### Delete 

DELETE {{baseUrl}}/groups/{{group_id}}/chats/{{chat_id}} HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

// -------------------- Get Users Info Public --------------- //

### Get all users 

GET {{baseUrl}}/users
      ?nickname=r

// -------------------- Join -------------------------------- //

### Get group
POST {{baseUrl}}/join/group
Content-Type: application/json
Authorization: {{authorization}}

{
  "group_id": "{{group_id}}"
}