# fly.toml app configuration file generated for kc-chat-real-time on 2024-09-04T13:46:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kc-chat-real-time'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
