@baseUrl = http://localhost:3000

### Ulternae
POST {{baseUrl}}/login
Content-Type: application/json

{
  "nickname": "Ulternae",
  "email": "Ulternae@gmail.com",
  "password": "1018",
  "sql" : "DROP TABLE users"
}

### Mth2
POST {{baseUrl}}/login
Content-Type: application/json

{
  "nickname": "Ultisaer Revternae",
  "email": "ultisaer.revternae@gmail.com",
  "password": "123",
  "sql" : "DROP TABLE users"
}

### Mth
POST {{baseUrl}}/login
Content-Type: application/json

{
  "nickname": "JHONATAN CASTILLO",
  "email": "001sargento001@gmail.com",
  "password": "103689422063917513318",
  "sql" : "DROP TABLE users"
}